name: Metrics

on:
  schedule:
    - cron: "0 2 1/7 * 6"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: commit calendar
        uses: joshuasp95/metrics@master
        with:
          token: ${{ secrets.metrics_token }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
